Repository Kwili/Website, pull requests merged in 2020-10, with the labels that each got.

#145 Cleaning code : removing all code linked to account
  src/Components/CheckLogin.js
  src/Components/Shared/Api/api.js
  src/Components/Shared/LogHandling/NotLogged.js
  src/Components/Shared/LogHandling/common.js
Labels: fix

#146 Tanguy/form
  src/Components/Landing/Components/Navbar.js
  src/Components/Shared/Navbar.js
Labels: hotfix

#147 rename "en savoir plus"
  src/Components/Landing/Landing.scss
  src/Components/Landing/LandingPage.js
Labels: hotfix

#148 Navbar : renamed Chatbot into Chat en ligne
  src/Components/Landing/Components/Navbar.js
Labels: hotfix

#149 Renamed chatbot into chat en ligne
  src/Components/Chat/ChatBotWidget.js
Labels: hotfix

#150 add new avatar
  src/Components/Chat/ChatBotWidget.js
  src/Images/doctor.png
Labels: enhancement

#153 [ui] chatbot now triggers a welcome message itself
  src/Components/Chat/ChatBotWidget.js
Labels: design

#154 [FIX] Updated all dependencies, removec all warning messages. Please …
  docker-compose.yml
  package.json
  src/__tests__/Redirections.spec.js
Labels: enhancement
