Repository Kwili/Website, pull requests merged in 2020-05, with the labels that each got.

#109 [fix] typo
  src/Components/Chat/ChatBotWidget.js
Labels: fix

#110 [fix] bugfixes
  src/Components/Map/Map.js
  src/Components/Map/Map.scss
  src/Components/Map/Shared/PopupDialog.scss
  src/Components/Map/Shared/RequestUberPopup.js
Labels: fix

#112 Tanguy/test
  package.json
  src/Components/Home/Home.js
  src/Components/Profile/Profile.js
  src/Components/Settings/Settings.js
  src/__tests__/Home.spec.js
  src/__tests__/Redirections.spec.js
  src/__tests__/__snapshots__/Home.spec.js.snap
  test
Labels: enhancement, fix

#113 [FIX] Ajout du lien google store
  src/Components/Landing/Components/Navbar.js
  src/Components/Landing/Components/PreviewSection.js
  src/__tests__/__snapshots__/404.spec.js.snap
  src/__tests__/__snapshots__/Navbar.spec.js.snap
Labels: enhancement
