Repository Kwili/Website, pull requests merged in 2020-08, with the labels that each got.

#136 Navbar update + changement de texte sur la landing
  src/Components/Landing/Components/Navbar.js
  src/Components/Landing/Components/PreviewSection.js
Labels: fix

#135 [design] change subtitle color theme
  src/Components/Home/home.scss
Labels: design

#137 Removed useless buttons
  src/Components/Landing/Components/ContactForm.js
Labels: fix

#138 [feat] doc.js comments
  src/Components/Chat/Api.js
  src/Components/Chat/ChatBotWidget.js
Labels: documentation

#139 auto-generated documentation landing + map
  jsdoc_conf.json
  package.json
  src/Components/Landing/Components/ContactForm.js
  src/Components/Landing/Components/FeaturesDescription.js
  src/Components/Landing/Components/Navbar.js
  src/Components/Landing/Components/PreviewSection.js
  src/Components/Landing/LandingPage.js
  src/Components/Map/Map.js
  src/Components/Map/Shared/MapOptions.js
  src/Components/Map/Shared/RequestUberPopup.js
  src/Components/Map/Shared/Slider.js
Labels: documentation

#140 Tanguy/form
  src/Components/Landing/Components/ContactForm.js
Labels: fix

#141 [feat] use of herokuapp for chatbot
  package.json
  src/Components/Chat/Api.js
Labels: enhancement
