Repository Kwili/Website, pull requests merged in 2020-03, with the labels that each got.

#96 Tanguy/webpack and ssl
  Dockerfile
  data/certbot/conf/csr/0000_csr-certbot.pem
  data/certbot/conf/options-ssl-nginx.conf
  data/certbot/conf/ssl-dhparams.pem
  data/certificates/certs/cert.pem
  data/certificates/private/privkey.pem
  data/nginx/app.conf
  docker-compose.yml
Labels: enhancement

#97 [dev] direct dialogflow connection with iframe
  .gitignore
  src/Components/Chat/Api.js
  src/Components/Chat/ChatBotWidget.css
  src/Components/Chat/ChatBotWidget.js
  src/Components/Chat/ChatBotWidget.scss
  src/Components/Chat/DialogFlow.js
  src/Components/Chat/search-bar.js
  src/Components/Landing/LandingPage.js
  src/Components/Login/Login.js
  src/Components/Profile/Profile.js
  src/Components/Shared/Api/api.js
  src/Components/Shared/Navbar.js
  src/Images/doctor.svg
  src/Images/stop.svg
Labels: enhancement

#98 [fix] 404 not found css
  src/Components/Shared/404/NotFound.js
Labels: design, fix

#99 Appel d'un UBER depuis la carte
  public/index.html
  src/Components/Map/Map.js
  src/Components/Map/Map.scss
  src/Components/Map/Shared/RequestUberPopup.js
Labels: design, enhancement

#100 kwili logo redirection to main page
  src/Components/Landing/Components/Navbar.js
Labels: design

#101 [dev minor] removed /chat route and add chatBot to navbar
  src/App.js
  src/Components/Landing/Components/Navbar.js
  src/Components/Landing/LandingPage.js
Labels: design, enhancement

#102 [dev] new chat widget
  src/Components/Chat/Api.js
  src/Components/Chat/BotCard.scss
  src/Components/Chat/Chat.js
  src/Components/Chat/Chat.scss
  src/Components/Chat/ChatBotWidget.js
  src/Components/Chat/ChatBotWidget.scss
  src/Components/Chat/DialogFlow.js
  src/Components/Chat/SearchBar.css
  src/Components/Chat/search-bar.js
Labels: design, enhancement
