Repository Kwili/Website, pull requests merged in 2020-11, with the labels that each got.

#155 Nginx removed access logs
  data/nginx/app.conf
Labels: fix

#156 Disabled docker log (RGPD)
  docker-compose.yml
Labels: fix

#157 [dev] implements server side quick replies
  src/Components/Chat/ChatBotWidget.js
Labels: enhancement

#158 [fix] removed language index when selecting quick replies
  src/Components/Chat/ChatBotWidget.js
Labels: bug, fix

#159 [ADD] Adding comments to docker-compose
  docker-compose.yml
Labels: documentation

#160 Tanguy/traduction
  .travis.yml
  package.json
  src/Components/Chat/Api.js
  src/Components/Chat/ChatBotWidget.js
  src/Components/Home/Home.js
  src/Components/Landing/Components/ContactForm.js
  src/Components/Landing/Components/FeaturesDescription.js
  src/Components/Landing/Components/Navbar.js
  src/Components/Landing/Components/PreviewSection.js
  src/Components/Landing/LandingPage.js
  src/Components/Map/Map.js
  src/Components/Map/Shared/HospitalInfoPopup.js
  src/Components/Map/Shared/RequestUberPopup.js
  src/Components/Map/Shared/ResultTypes.js
  src/Components/Prescription/Prescription.js
  src/Components/Prescription/Prescription.scss
  src/Components/Prescription/View.js
  src/Components/Shared/404/NotFound.js
  src/Translations/en.json
  src/Translations/fr.json
  src/index.js
Labels: enhancement

#161 [FIX] Fixed small typo
  src/Translations/en.json
Labels: hotfix

#162 Ui/minor fixes
  src/Components/Home/Home.js
  src/Components/Home/home.scss
  src/Components/Landing/Components/ContactForm.js
  src/Components/Landing/Components/EmailModal.js
  src/Components/Landing/Components/FeaturesDescription.js
  src/Components/Landing/Components/Navbar.js
  src/Components/Landing/Components/PreviewSection.js
  src/Components/Landing/Landing.scss
  src/Components/Landing/LandingPage.js
  src/Images/desktop_1.png
  src/Images/desktop_2.png
  src/Images/desktop_3.png
  src/Images/phone_1.png
  src/Images/phone_2.png
  src/Images/phone_3.png
  src/Translations/en.json
  src/Translations/fr.json
  src/__tests__/Redirections.spec.js
Labels: enhancement

#163 [FIX] Removed old 404 page image
  src/Components/Shared/404/img/bg.jpg
Labels: fix

#164 [FIX] Fixed ugly chat colors
  src/Components/Chat/ChatBotWidget.scss
Labels: enhancement

#165 [FIX] Mobile screen and chat issue
  src/Components/Chat/ChatBotWidget.scss
Labels: fix

#166 [FIX] Close button hidden on mobile screen
  src/Components/Chat/ChatBotWidget.scss
Labels: hotfix

#167 [fix] badgeCount now reset when component mounted
  src/Components/Chat/ChatBotWidget.js
  src/Components/Landing/Components/ContactForm.js
Labels: bug, fix

#169 Tanguy/test
  public/index.html
  src/Components/Map/Map.js
  src/Components/PrivacyPolicy/PrivacyPolicy.js
  src/Translations/en.json
  src/Translations/fr.json
Labels: bug, fix
