Repository Kwili/Website, pull requests merged in 2020-01, with the labels that each got.

#83 Lbl/chat
  package.json
  src/App.js
  src/Components/Chat/Api.js
  src/Components/Chat/BotCard.scss
  src/Components/Chat/Chat.js
  src/Components/Chat/Chat.scss
  src/Components/Chat/ChatBotWidget.css
  src/Components/Chat/ChatBotWidget.js
  src/Components/Chat/View.js
  src/Components/Chat/search-bar.js
  src/Components/Login/Login.js
  src/Components/Profile/Profile.js
  src/Components/Shared/Api/api.js
  src/index.js
Labels: enhancement

#84 [fix] api public endpoints
  src/Components/Chat/Api.js
  src/Components/Shared/Api/api.js
Labels: hotfix

#82 Tanguy/profiles
  config/webpack.config.dev.js
  src/App.js
  src/Components/Chat/Chat.js
  src/Components/CheckLogin.js
  src/Components/Landing/NavbarLanding/NavbarLanding.js
  src/Components/Login/Login.js
  src/Components/Prescription/View.js
  src/Components/Profile/Profile.js
  src/Components/Settings/Settings.js
Labels: enhancement

#85 Lbl/fix requests
  src/Components/Chat/Api.js
  src/Components/Login/Login.js
  src/Components/Register/Register.js
  src/Components/Shared/Api/api.js
Labels: hotfix

#88 [dev minor] changed /Profile design (JB Melet)
  src/Components/Profile/Profile.js
  src/Components/Profile/Profile.scss
  src/Components/Settings/Settings.js
Labels: design

#89 Redirection vers le profile
  src/Components/Landing/NavbarLanding/NavbarLanding.js
Labels: hotfix

#90 Tanguy/profiles
  src/Components/Landing/NavbarLanding/NavbarLanding.js
Labels: hotfix
