Repository Kwili/Website, pull requests merged in 2020-04, with the labels that each got.

#103 [dev] ajout des intents avec boutons et API en https
  src/Components/Chat/Api.js
  src/Components/Chat/ChatBotWidget.js
Labels: design, enhancement

#104 Mise à jour css carte et page 404
  src/Components/Landing/Landing.scss
  src/Components/Map/Map.js
  src/Components/Map/Map.scss
  src/Components/Map/Shared/MapOptions.js
  src/Components/Shared/404/NotFound.js
  src/Components/Shared/404/css/NotFound.scss
  src/Components/Shared/404/css/style.css
Labels: design

#107 Tanguy/test
  .travis.yml
  package.json
  src/App.js
  src/Components/Landing/Components/Navbar.js
  src/__tests__/404.spec.js
  src/__tests__/Navbar.spec.js
  src/__tests__/__snapshots__/404.spec.js.snap
  src/__tests__/__snapshots__/Navbar.spec.js.snap
Labels: enhancement

#108 [dev minor] chatbot displays links as hyper links
  package.json
  src/Components/Chat/ChatBotWidget.js
Labels: design, enhancement
